# Generated by Django 4.2.4 on 2023-12-22 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('related_to', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='documents/')),
                ('file2', models.FileField(upload_to='documents/')),
                ('file3', models.FileField(upload_to='documents/')),
                ('file4', models.FileField(upload_to='documents/')),
                ('file5', models.FileField(upload_to='documents/')),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myApi.userform')),
            ],
        ),
    ]
