# Generated by Django 4.2.4 on 2023-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_userform_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPagesApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AllPAgesByAgentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentEmail', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('pdf_file1', models.FileField(upload_to='pdf_files/')),
                ('pdf_file2', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf_file3', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf_file4', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
        migrations.CreateModel(
            name='UserOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pdf_file1', models.FileField(upload_to='pdf_files/')),
                ('pdf_file2', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf_file3', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf_file4', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
    ]
