# Generated by Django 4.2.4 on 2023-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0003_allpagesapi_allpagesbyagentcontrol_useroutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file1', models.FileField(upload_to='pdf_files/')),
                ('pdf_file2', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf_file3', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf_file4', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
    ]
